CREATE PROC FI_SP_ConsBeneficiario
	@IDCLIENTE BIGINT
AS
BEGIN
	IF(ISNULL(@IDCLIENTE,0) = 0)
		SELECT NOME, ID, CPF, IDCLIENTE FROM Beneficiarios WITH(NOLOCK)
	ELSE
		SELECT NOME, ID, CPF, IDCLIENTE FROM Beneficiarios WITH(NOLOCK) WHERE IDCLIENTE = @IDCLIENTE
END