ALTER PROC FI_SP_VerificaCliente
	@CPF VARCHAR(11),
	@ID BIGINT
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT 1 FROM CLIENTES WHERE CPF = @CPF
	ELSE
		SELECT 1 FROM CLIENTES WHERE CPF = @CPF AND ID != @ID
END